#!/usr/bin/env bash
# Assemble a distributable bundle of leanlift under dist/:
#
#   dist/leanlift-<version>-<platform>/
#     bin/lift               the engine (links only base-system libs — see the
#                            shared-library manifest written into DIST.md)
#     lean/                  audited Lean support sources (NO .oleans: they are
#                            toolchain-version-locked; rebuilt on first run)
#     examples/              kernels, proof fragments, models
#     tests/run.sh           the suite (external-tool sections self-skip)
#     scripts/               build_cpp2rust.sh + build_aeneas.sh — the complete,
#                            pinned build info for the OPTIONAL external deps
#     vendor/cpp2rust/       (only when built on this host) the statically-
#                            linked translator + preprocessed rules, laid out
#                            as LEANLIFT_CPP2RUST expects; caveat in DIST.md
#     DIST.md                layout, runtime requirements, dep-build info,
#                            ldd manifest — generated by this script
#
# plus dist/leanlift-<version>-<platform>.tar.gz of the same tree.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION=$(grep -m1 '^version' Cargo.toml | sed 's/.*"\(.*\)"/\1/')
PLAT="$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)"
NAME="leanlift-$VERSION-$PLAT"
DIST="dist/$NAME"

echo "== build the engine =="
cargo build --release

echo "== assemble $DIST =="
rm -rf "$DIST" && mkdir -p "$DIST"/{bin,scripts,tests}
cp target/release/lift "$DIST/bin/"
cp README.md SPEC.md SKILL.md "$DIST/"
cp scripts/build_cpp2rust.sh scripts/build_aeneas.sh "$DIST/scripts/"
cp tests/run.sh "$DIST/tests/"
# Runtime assets. The engine resolves `lean/` and `examples/` relative to the
# working directory, so the bundle root is the run directory.
rsync -a --exclude '*.olean' lean "$DIST/"
rsync -a --exclude 'target' --exclude '*.llbc' examples "$DIST/"

# Optional vendored cpp2rust: statically linked against LLVM 22, so the binary
# itself needs only base-system shared libs. Mirrors the checkout layout so
# `LEANLIFT_CPP2RUST=<bundle>/vendor/cpp2rust` just works.
C2R="${LEANLIFT_CPP2RUST:-$HOME/work/_verif-tools/cpp2rust}"
VENDORED=no
if [ -x "$C2R/build/cpp2rust/cpp2rust" ] && [ -d "$C2R/build/rules" ]; then
  VENDORED=yes
  mkdir -p "$DIST/vendor/cpp2rust/build/cpp2rust"
  cp "$C2R/build/cpp2rust/cpp2rust" "$DIST/vendor/cpp2rust/build/cpp2rust/"
  rsync -a "$C2R/build/rules" "$DIST/vendor/cpp2rust/build/"
  [ -f "$C2R/LICENSE" ] && cp "$C2R/LICENSE" "$DIST/vendor/cpp2rust/LICENSE"
fi

echo "== write DIST.md (incl. shared-library manifest) =="
manifest() { ldd "$1" | grep -v 'linux-vdso' | sed 's/^\s*/    /;s/ (0x[0-9a-f]*)$//'; }
{
  cat <<EOF
# leanlift $VERSION — binary distribution ($PLAT)

Run everything from THIS directory (the engine resolves \`lean/\` and
\`examples/\` relative to the working directory):

\`\`\`bash
./bin/lift verify avg          # engine + Lean support lib only
./tests/run.sh                 # full suite; external-tool sections self-skip
\`\`\`

## Runtime requirements

| stage | needs |
|---|---|
| \`bin/lift\` itself | base glibc only (manifest below — nothing to bundle) |
| source oracles | \`c++\` (any C++17 compiler); \`go\` / \`forge\` only for Go/Solidity examples |
| Lean stages (verify/prove) | \`lean\`/\`lake\` via [elan](https://github.com/leanprover/elan); the support lib recompiles on first run (no .oleans shipped — they are toolchain-version-locked) |
| \`rust-*\` + \`c2r-*\` examples, \`lift prove\` | Charon+Aeneas — build with \`scripts/build_aeneas.sh\` |
| \`c2r-*\` examples | cpp2rust — vendored copy (below) or \`scripts/build_cpp2rust.sh\` |

Absent tools are a clean SKIP (exit 0), never a failure.

## Building the external deps (the scripts are the authoritative info)

- \`scripts/build_cpp2rust.sh\` — clones the pinned cpp2rust commit and builds
  it. Needs clang/libclang ≥ 21; if the system toolchain is older it
  auto-downloads the official LLVM 22.1.8 release tarball (~1.7 GB, no sudo).
  Also builds the libcc2rs runtime (an rlib — rustc-version-locked, hence not
  shipped here; only needed for pointer kernels, which the c2r lane rejects).
- \`scripts/build_aeneas.sh\` — clones and builds Charon + Aeneas (OCaml; needs
  opam with a 5.3.0 switch; the opam package list in the script is complete).
  First Lean run: \`lake exe cache get && lake build\` in
  \`<aeneas>/backends/lean\` fetches the mathlib olean cache.
- Both install out-of-tree into \`~/work/_verif-tools/\` and are located via
  \`LEANLIFT_CPP2RUST\` / \`LEANLIFT_AENEAS\`.

## Shared-library manifest

\`bin/lift\`:
$(manifest target/release/lift)
EOF
  if [ "$VENDORED" = yes ]; then
    cat <<EOF

\`vendor/cpp2rust/build/cpp2rust/cpp2rust\` (LLVM linked STATICALLY):
$(manifest "$C2R/build/cpp2rust/cpp2rust")

## Vendored cpp2rust — portability caveat

The vendored binary embeds two absolute paths from its build host at compile
time (\`-resource-dir=<llvm>/lib/clang/22\` for clang's builtin headers, and
its \`compat/\` include dir). It therefore works out of the box only where
those paths exist — the build host, or a machine with the same
\`~/work/_verif-tools\` prefix. Elsewhere, run \`scripts/build_cpp2rust.sh\`
(fully automated) instead of using the vendored copy. To use it:

\`\`\`bash
export LEANLIFT_CPP2RUST=\$PWD/vendor/cpp2rust
./bin/lift verify c2r-avg && ./bin/lift prove c2r-isqrt
\`\`\`
EOF
  else
    printf '\n(vendor/cpp2rust not included: the tool was not built on the dist host —\nrun scripts/build_cpp2rust.sh on the target machine.)\n'
  fi
} > "$DIST/DIST.md"

echo "== tarball =="
tar -C dist -czf "dist/$NAME.tar.gz" "$NAME"
echo "DONE:"
du -sh "$DIST" "dist/$NAME.tar.gz"
