//! Code export (PLAN-models §6) — a model → a runnable executor in C++ / Rust /
//! Go, plus the **loop closure** (§6.3): the generated executor is difftested
//! against the native model semantics over random action traces, so a code
//! generator bug shows up as a trace mismatch. This is the model-axis analogue
//! of the engine's L1 ("LLM proposes, algorithm disposes") — here the exporter
//! proposes and the native checker disposes.
//!
//! All three languages share one **trace protocol** so their output is directly
//! comparable to the native simulator: read traces from stdin (one per line,
//! space-separated event names); for each, print the visited state names, a `!`
//! after any forbidden state (the §6.2 runtime monitor), and `BLOCKED` when an
//! event is refused. Scope: the LTS families (FSM, BT — BT compiles to an LTS).
//! Petri/CPN/GSPN code export is deferred (§6.7 etc.).

use super::ir::{Lts, Model, PtNet};

#[derive(Clone, Copy, PartialEq)]
pub enum Lang {
    Rust,
    Cpp,
    Go,
    Dot,
}

impl Lang {
    pub fn parse(s: &str) -> Option<Lang> {
        match s {
            "rust" | "rs" => Some(Lang::Rust),
            "cpp" | "c++" | "cc" => Some(Lang::Cpp),
            "go" | "golang" => Some(Lang::Go),
            "dot" | "graphviz" => Some(Lang::Dot),
            _ => None,
        }
    }
    pub fn ext(self) -> &'static str {
        match self {
            Lang::Rust => "rs",
            Lang::Cpp => "cpp",
            Lang::Go => "go",
            Lang::Dot => "dot",
        }
    }
    pub fn tag(self) -> &'static str {
        match self {
            Lang::Rust => "rust",
            Lang::Cpp => "c++",
            Lang::Go => "go",
            Lang::Dot => "dot",
        }
    }
    /// Whether the output is a compilable/runnable executor (vs visualization).
    pub fn executable(self) -> bool {
        self != Lang::Dot
    }
}

/// A valid identifier for a code variant: non-alphanumerics → `_`, digit-leading
/// gets an `S` prefix. Distinct model names stay distinct (subset/product names
/// like `Navigate|Delocalized` → `Navigate_Delocalized`).
fn vid(name: &str) -> String {
    let mut s: String = name.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect();
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(true) {
        s.insert(0, 'S');
    }
    s
}

/// Emit the executor source for `lts` in `lang`.
pub fn emit(lts: &Lts, lang: Lang) -> String {
    match lang {
        Lang::Rust => rust(lts),
        Lang::Cpp => cpp(lts),
        Lang::Go => go(lts),
        Lang::Dot => dot(lts),
    }
}

/// Graphviz DOT for visualization (PLAN-models §1.5): the initial state is
/// double-circled, forbidden states are filled red, edges are labelled by event.
fn dot(lts: &Lts) -> String {
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model export --lang dot`.\n");
    o.push_str(&format!("digraph {} {{\n  rankdir=LR;\n  node [shape=circle];\n", "model"));
    o.push_str("  __start [shape=point];\n");
    o.push_str(&format!("  __start -> {:?};\n", lts.initial));
    for s in &lts.states {
        if lts.forbid.iter().any(|f| f == s) {
            o.push_str(&format!("  {s:?} [style=filled, fillcolor=\"#ffcccc\"];\n"));
        }
        if s == &lts.initial {
            o.push_str(&format!("  {s:?} [shape=doublecircle];\n"));
        }
    }
    // Deterministic edge order (the transitions map is unordered).
    for from in &lts.states {
        for ev in &lts.alphabet {
            if let Some(to) = lts.transitions.get(&(from.clone(), ev.clone())) {
                o.push_str(&format!("  {from:?} -> {to:?} [label={ev:?}];\n"));
            }
        }
    }
    o.push_str("}\n");
    o
}

// --- the native reference simulator (the oracle) ----------------------------- //

/// Run any `Model` over one trace, producing the protocol output line: initial
/// state encoding, then per action the next state (`!`-flagged if forbidden), or
/// `BLOCKED` when refused. Identical to what every generated executor prints —
/// states are the model's canonical encoding (an FSM/BT state name, a Petri
/// marking like `1,0,0,0,0`).
pub fn native_trace(model: &dyn Model, trace: &[String]) -> String {
    let mut s = model.initial();
    let mut out = vec![s.clone()];
    if model.forbidden(&s).is_some() {
        out.push("!".into());
    }
    for ev in trace {
        match model.step(&s, ev) {
            Some(s2) => {
                s = s2;
                out.push(s.clone());
                if model.forbidden(&s).is_some() {
                    out.push("!".into());
                }
            }
            None => {
                out.push("BLOCKED".into());
                break;
            }
        }
    }
    out.join(" ")
}

/// Deterministic action traces from `alphabet` (fixed seed ⇒ reproducible).
/// Generates `n` traces of length up to `max_len`; an empty alphabet ⇒ just the
/// single empty trace (a quiescent model).
pub fn gen_traces(alphabet: &[String], n: usize, max_len: usize, seed: u64) -> Vec<Vec<String>> {
    if alphabet.is_empty() {
        return vec![vec![]];
    }
    let mut state = seed;
    let mut next = || {
        // xorshift64
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        state
    };
    let mut traces = Vec::with_capacity(n);
    for _ in 0..n {
        let len = (next() as usize) % (max_len + 1);
        let trace: Vec<String> = (0..len).map(|_| alphabet[(next() as usize) % alphabet.len()].clone()).collect();
        traces.push(trace);
    }
    traces
}

// --- Petri executors (marking = array of counts) ----------------------------- //

/// Transition names of a PT-net (its action alphabet, for `gen_traces`).
pub fn petri_alphabet(net: &PtNet) -> Vec<String> {
    net.transitions.iter().map(|t| t.name.clone()).collect()
}

/// Emit a PT-net executor in `lang` (Rust/C++/Go). States are the canonical
/// marking encoding (`1,0,0,…`) so output matches the native simulator.
pub fn emit_petri(net: &PtNet, lang: Lang) -> String {
    match lang {
        Lang::Rust => petri_rust(net),
        Lang::Cpp => petri_cpp(net),
        Lang::Go => petri_go(net),
        Lang::Dot => petri_dot(net),
    }
}

/// Guard expression `m[i] >= c && …` over a transition's pre-set (`true` if none).
fn pre_guard(net: &PtNet, t: usize, idx: impl Fn(usize) -> String) -> String {
    let pre = &net.transitions[t].pre;
    let conds: Vec<String> = (0..net.places.len())
        .filter(|&p| pre[p] > 0)
        .map(|p| format!("{} >= {}", idx(p), pre[p]))
        .collect();
    if conds.is_empty() { "true".to_string() } else { conds.join(" && ") }
}

/// Forbidden expression: OR of `(sum of bound places) > max` over the bounds.
fn forbidden_expr(net: &PtNet, idx: impl Fn(usize) -> String) -> String {
    if net.bounds.is_empty() {
        return "false".to_string();
    }
    net.bounds
        .iter()
        .map(|b| {
            let sum = b.places.iter().map(|&p| idx(p)).collect::<Vec<_>>().join(" + ");
            format!("({sum} > {})", b.max)
        })
        .collect::<Vec<_>>()
        .join(" || ")
}

fn petri_rust(net: &PtNet) -> String {
    let n = net.places.len();
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model export --lang rust` (PT-net) — DO NOT EDIT.\n");
    o.push_str("#![allow(dead_code, unused_comparisons)]\nuse std::io::Read;\n\n");
    o.push_str(&format!("const N: usize = {n};\n\n"));

    o.push_str("fn enabled(m: &[u32; N], t: usize) -> bool {\n    match t {\n");
    for (t, _) in net.transitions.iter().enumerate() {
        o.push_str(&format!("        {t} => {},\n", pre_guard(net, t, |p| format!("m[{p}]"))));
    }
    o.push_str("        _ => false,\n    }\n}\n\n");

    o.push_str("fn fire(m: &[u32; N], t: usize) -> [u32; N] {\n    let mut r = *m;\n    match t {\n");
    for (t, tr) in net.transitions.iter().enumerate() {
        let ups: Vec<String> = (0..n)
            .filter(|&p| tr.pre[p] != 0 || tr.post[p] != 0)
            .map(|p| {
                let mut e = format!("r[{p}]");
                if tr.pre[p] > 0 {
                    e.push_str(&format!(" - {}", tr.pre[p]));
                }
                if tr.post[p] > 0 {
                    e.push_str(&format!(" + {}", tr.post[p]));
                }
                format!("r[{p}] = {e};")
            })
            .collect();
        o.push_str(&format!("        {t} => {{ {} }}\n", ups.join(" ")));
    }
    o.push_str("        _ => {}\n    }\n    r\n}\n\n");

    o.push_str("fn tname(s: &str) -> Option<usize> {\n    match s {\n");
    for (t, tr) in net.transitions.iter().enumerate() {
        o.push_str(&format!("        {:?} => Some({t}),\n", tr.name));
    }
    o.push_str("        _ => None,\n    }\n}\n\n");

    o.push_str("fn enc(m: &[u32; N]) -> String { m.iter().map(|c| c.to_string()).collect::<Vec<_>>().join(\",\") }\n\n");
    o.push_str(&format!(
        "fn forbidden(m: &[u32; N]) -> bool {{ {} }}\n\n",
        forbidden_expr(net, |p| format!("m[{p}]"))
    ));

    let init = net.initial.iter().map(|c| c.to_string()).collect::<Vec<_>>().join(", ");
    o.push_str(&format!(
        "fn main() {{\n\
        \x20   let init: [u32; N] = [{init}];\n\
        \x20   let mut input = String::new();\n\
        \x20   std::io::stdin().read_to_string(&mut input).unwrap();\n\
        \x20   for line in input.lines() {{\n\
        \x20       let mut m = init;\n\
        \x20       let mut out = vec![enc(&m)];\n\
        \x20       if forbidden(&m) {{ out.push(\"!\".to_string()); }}\n\
        \x20       for tok in line.split_whitespace() {{\n\
        \x20           match tname(tok) {{\n\
        \x20               Some(t) => {{ if enabled(&m, t) {{ m = fire(&m, t); out.push(enc(&m)); if forbidden(&m) {{ out.push(\"!\".to_string()); }} }} else {{ out.push(\"BLOCKED\".to_string()); break; }} }}\n\
        \x20               None => {{ out.push(\"BADEVENT\".to_string()); break; }}\n\
        \x20           }}\n\
        \x20       }}\n\
        \x20       println!(\"{{}}\", out.join(\" \"));\n\
        \x20   }}\n}}\n"
    ));
    o
}

fn petri_cpp(net: &PtNet) -> String {
    let n = net.places.len();
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model export --lang c++` (PT-net) — DO NOT EDIT.\n");
    o.push_str("#include <array>\n#include <iostream>\n#include <sstream>\n#include <string>\n\n");
    o.push_str(&format!("static const int N = {n};\nusing M = std::array<unsigned,N>;\n\n"));

    o.push_str("bool enabled(const M& m, int t) {\n    switch (t) {\n");
    for (t, _) in net.transitions.iter().enumerate() {
        o.push_str(&format!("    case {t}: return {};\n", pre_guard(net, t, |p| format!("m[{p}]"))));
    }
    o.push_str("    default: return false;\n    }\n}\n\n");

    o.push_str("M fire(M m, int t) {\n    switch (t) {\n");
    for (t, tr) in net.transitions.iter().enumerate() {
        let ups: Vec<String> = (0..n)
            .filter(|&p| tr.pre[p] != 0 || tr.post[p] != 0)
            .map(|p| {
                let mut e = format!("m[{p}]");
                if tr.pre[p] > 0 {
                    e.push_str(&format!(" - {}", tr.pre[p]));
                }
                if tr.post[p] > 0 {
                    e.push_str(&format!(" + {}", tr.post[p]));
                }
                format!("m[{p}] = {e};")
            })
            .collect();
        o.push_str(&format!("    case {t}: {{ {} }} break;\n", ups.join(" ")));
    }
    o.push_str("    }\n    return m;\n}\n\n");

    o.push_str("int tname(const std::string& s) {\n");
    for (t, tr) in net.transitions.iter().enumerate() {
        o.push_str(&format!("    if (s == {:?}) return {t};\n", tr.name));
    }
    o.push_str("    return -1;\n}\n\n");

    o.push_str("std::string enc(const M& m) {\n    std::string r;\n    for (int i=0;i<N;i++){ if(i) r+=\",\"; r+=std::to_string(m[i]); }\n    return r;\n}\n\n");
    o.push_str(&format!(
        "bool forbidden(const M& m) {{ return {}; }}\n\n",
        forbidden_expr(net, |p| format!("m[{p}]"))
    ));

    let init = net.initial.iter().map(|c| c.to_string()).collect::<Vec<_>>().join(", ");
    o.push_str(&format!(
        "int main() {{\n\
        \x20   M init = {{{init}}};\n\
        \x20   std::string line;\n\
        \x20   while (std::getline(std::cin, line)) {{\n\
        \x20       M m = init;\n\
        \x20       std::string out = enc(m);\n\
        \x20       if (forbidden(m)) out += \" !\";\n\
        \x20       std::istringstream iss(line); std::string tok;\n\
        \x20       while (iss >> tok) {{\n\
        \x20           int t = tname(tok);\n\
        \x20           if (t < 0) {{ out += \" BADEVENT\"; break; }}\n\
        \x20           if (!enabled(m, t)) {{ out += \" BLOCKED\"; break; }}\n\
        \x20           m = fire(m, t); out += \" \"; out += enc(m);\n\
        \x20           if (forbidden(m)) out += \" !\";\n\
        \x20       }}\n\
        \x20       std::cout << out << \"\\n\";\n\
        \x20   }}\n\
        \x20   return 0;\n}}\n"
    ));
    o
}

fn petri_go(net: &PtNet) -> String {
    let n = net.places.len();
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model export --lang go` (PT-net) — DO NOT EDIT.\n");
    o.push_str("package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\n");
    o.push_str(&format!("const N = {n}\ntype M = [N]uint\n\n"));

    o.push_str("func enabled(m M, t int) bool {\n\tswitch t {\n");
    for (t, _) in net.transitions.iter().enumerate() {
        o.push_str(&format!("\tcase {t}:\n\t\treturn {}\n", pre_guard(net, t, |p| format!("m[{p}]"))));
    }
    o.push_str("\t}\n\treturn false\n}\n\n");

    o.push_str("func fire(m M, t int) M {\n\tswitch t {\n");
    for (t, tr) in net.transitions.iter().enumerate() {
        let ups: Vec<String> = (0..n)
            .filter(|&p| tr.pre[p] != 0 || tr.post[p] != 0)
            .map(|p| {
                let mut e = format!("m[{p}]");
                if tr.pre[p] > 0 {
                    e.push_str(&format!(" - {}", tr.pre[p]));
                }
                if tr.post[p] > 0 {
                    e.push_str(&format!(" + {}", tr.post[p]));
                }
                format!("m[{p}] = {e}")
            })
            .collect();
        o.push_str(&format!("\tcase {t}:\n\t\t{}\n", ups.join("; ")));
    }
    o.push_str("\t}\n\treturn m\n}\n\n");

    o.push_str("func tname(s string) int {\n\tswitch s {\n");
    for (t, tr) in net.transitions.iter().enumerate() {
        o.push_str(&format!("\tcase {:?}:\n\t\treturn {t}\n", tr.name));
    }
    o.push_str("\t}\n\treturn -1\n}\n\n");

    o.push_str("func enc(m M) string {\n\tp := make([]string, N)\n\tfor i := 0; i < N; i++ { p[i] = strconv.Itoa(int(m[i])) }\n\treturn strings.Join(p, \",\")\n}\n\n");
    o.push_str(&format!(
        "func forbidden(m M) bool {{ return {} }}\n\n",
        forbidden_expr(net, |p| format!("m[{p}]"))
    ));

    let init = net.initial.iter().map(|c| c.to_string()).collect::<Vec<_>>().join(", ");
    o.push_str(&format!(
        "func main() {{\n\
        \tinit := M{{{init}}}\n\
        \tsc := bufio.NewScanner(os.Stdin)\n\
        \tsc.Buffer(make([]byte, 1024*1024), 1024*1024)\n\
        \tfor sc.Scan() {{\n\
        \t\tm := init\n\
        \t\tout := []string{{enc(m)}}\n\
        \t\tif forbidden(m) {{ out = append(out, \"!\") }}\n\
        \t\tfor _, tok := range strings.Fields(sc.Text()) {{\n\
        \t\t\tt := tname(tok)\n\
        \t\t\tif t < 0 {{ out = append(out, \"BADEVENT\"); break }}\n\
        \t\t\tif !enabled(m, t) {{ out = append(out, \"BLOCKED\"); break }}\n\
        \t\t\tm = fire(m, t); out = append(out, enc(m))\n\
        \t\t\tif forbidden(m) {{ out = append(out, \"!\") }}\n\
        \t\t}}\n\
        \t\tfmt.Println(strings.Join(out, \" \"))\n\
        \t}}\n}}\n"
    ));
    o
}

/// DOT for a PT-net: places (circles) and transitions (boxes) with weighted arcs.
fn petri_dot(net: &PtNet) -> String {
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model export --lang dot` (PT-net).\n");
    o.push_str("digraph net {\n  rankdir=LR;\n");
    for (i, p) in net.places.iter().enumerate() {
        let tok = net.initial[i];
        let label = if tok > 0 { format!("{p}\\n({tok})") } else { p.clone() };
        o.push_str(&format!("  \"p_{p}\" [shape=circle, label={label:?}];\n"));
    }
    for tr in &net.transitions {
        o.push_str(&format!("  \"t_{}\" [shape=box, label={:?}];\n", tr.name, tr.name));
    }
    for tr in &net.transitions {
        for (p, &c) in tr.pre.iter().enumerate() {
            if c > 0 {
                o.push_str(&format!("  \"p_{}\" -> \"t_{}\";\n", net.places[p], tr.name));
            }
        }
        for (p, &c) in tr.post.iter().enumerate() {
            if c > 0 {
                o.push_str(&format!("  \"t_{}\" -> \"p_{}\";\n", tr.name, net.places[p]));
            }
        }
    }
    o.push_str("}\n");
    o
}

// --- Rust --------------------------------------------------------------------- //

fn rust(lts: &Lts) -> String {
    let sv = |s: &str| vid(s);
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model export --lang rust` — DO NOT EDIT.\n");
    o.push_str("#![allow(non_camel_case_types, dead_code, unreachable_patterns)]\nuse std::io::Read;\n\n");

    o.push_str("#[derive(Clone, Copy, PartialEq)]\nenum State {\n");
    for s in &lts.states {
        o.push_str(&format!("    {},\n", sv(s)));
    }
    o.push_str("}\n\n#[derive(Clone, Copy, PartialEq)]\nenum Event {\n");
    for e in &lts.alphabet {
        o.push_str(&format!("    {},\n", sv(e)));
    }
    o.push_str("}\n\n");

    o.push_str("fn step(s: State, e: Event) -> Option<State> {\n    match (s, e) {\n");
    for s in &lts.states {
        for e in &lts.alphabet {
            if let Some(t) = lts.transitions.get(&(s.clone(), e.clone())) {
                o.push_str(&format!("        (State::{}, Event::{}) => Some(State::{}),\n", sv(s), sv(e), sv(t)));
            }
        }
    }
    o.push_str("        _ => None,\n    }\n}\n\n");

    o.push_str("fn name(s: State) -> &'static str {\n    match s {\n");
    for s in &lts.states {
        o.push_str(&format!("        State::{} => {:?},\n", sv(s), s));
    }
    o.push_str("    }\n}\n\n");

    o.push_str("fn parse_event(s: &str) -> Option<Event> {\n    match s {\n");
    for e in &lts.alphabet {
        o.push_str(&format!("        {:?} => Some(Event::{}),\n", e, sv(e)));
    }
    o.push_str("        _ => None,\n    }\n}\n\n");

    o.push_str("fn forbidden(s: State) -> bool {\n    match s {\n");
    for f in &lts.forbid {
        o.push_str(&format!("        State::{} => true,\n", sv(f)));
    }
    o.push_str("        _ => false,\n    }\n}\n\n");

    o.push_str(&format!(
        "fn main() {{\n\
        \x20   let mut input = String::new();\n\
        \x20   std::io::stdin().read_to_string(&mut input).unwrap();\n\
        \x20   for line in input.lines() {{\n\
        \x20       let mut s = State::{};\n\
        \x20       let mut out = vec![name(s).to_string()];\n\
        \x20       if forbidden(s) {{ out.push(\"!\".to_string()); }}\n\
        \x20       for tok in line.split_whitespace() {{\n\
        \x20           match parse_event(tok) {{\n\
        \x20               Some(e) => match step(s, e) {{\n\
        \x20                   Some(s2) => {{ s = s2; out.push(name(s).to_string()); if forbidden(s) {{ out.push(\"!\".to_string()); }} }}\n\
        \x20                   None => {{ out.push(\"BLOCKED\".to_string()); break; }}\n\
        \x20               }},\n\
        \x20               None => {{ out.push(\"BADEVENT\".to_string()); break; }}\n\
        \x20           }}\n\
        \x20       }}\n\
        \x20       println!(\"{{}}\", out.join(\" \"));\n\
        \x20   }}\n}}\n",
        sv(&lts.initial)
    ));
    o
}

// --- C++ ---------------------------------------------------------------------- //

fn cpp(lts: &Lts) -> String {
    let sv = |s: &str| vid(s);
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model export --lang c++` — DO NOT EDIT.\n");
    o.push_str("#include <iostream>\n#include <optional>\n#include <sstream>\n#include <string>\n\n");

    o.push_str("enum class State {");
    o.push_str(&lts.states.iter().map(|s| sv(s)).collect::<Vec<_>>().join(", "));
    o.push_str("};\nenum class Event {");
    o.push_str(&lts.alphabet.iter().map(|e| sv(e)).collect::<Vec<_>>().join(", "));
    o.push_str("};\n\n");

    o.push_str("std::optional<State> step(State s, Event e) {\n    switch (s) {\n");
    for s in &lts.states {
        let arms: Vec<(String, String)> = lts
            .alphabet
            .iter()
            .filter_map(|e| lts.transitions.get(&(s.clone(), e.clone())).map(|t| (sv(e), sv(t))))
            .collect();
        if arms.is_empty() {
            continue;
        }
        o.push_str(&format!("    case State::{}: switch (e) {{\n", sv(s)));
        for (e, t) in arms {
            o.push_str(&format!("        case Event::{e}: return State::{t};\n"));
        }
        o.push_str("        default: return std::nullopt;\n    }\n");
    }
    o.push_str("    default: return std::nullopt;\n    }\n}\n\n");

    o.push_str("const char* name(State s) {\n    switch (s) {\n");
    for s in &lts.states {
        o.push_str(&format!("    case State::{}: return {:?};\n", sv(s), s));
    }
    o.push_str("    }\n    return \"?\";\n}\n\n");

    o.push_str("std::optional<Event> parse_event(const std::string& s) {\n");
    for e in &lts.alphabet {
        o.push_str(&format!("    if (s == {:?}) return Event::{};\n", e, sv(e)));
    }
    o.push_str("    return std::nullopt;\n}\n\n");

    o.push_str("bool forbidden(State s) {\n    switch (s) {\n");
    for f in &lts.forbid {
        o.push_str(&format!("    case State::{}: return true;\n", sv(f)));
    }
    o.push_str("    default: return false;\n    }\n}\n\n");

    o.push_str(&format!(
        "int main() {{\n\
        \x20   std::string line;\n\
        \x20   while (std::getline(std::cin, line)) {{\n\
        \x20       State s = State::{};\n\
        \x20       std::string out = name(s);\n\
        \x20       if (forbidden(s)) out += \" !\";\n\
        \x20       std::istringstream iss(line);\n\
        \x20       std::string tok;\n\
        \x20       while (iss >> tok) {{\n\
        \x20           auto e = parse_event(tok);\n\
        \x20           if (!e) {{ out += \" BADEVENT\"; break; }}\n\
        \x20           auto s2 = step(s, *e);\n\
        \x20           if (!s2) {{ out += \" BLOCKED\"; break; }}\n\
        \x20           s = *s2; out += \" \"; out += name(s);\n\
        \x20           if (forbidden(s)) out += \" !\";\n\
        \x20       }}\n\
        \x20       std::cout << out << \"\\n\";\n\
        \x20   }}\n\
        \x20   return 0;\n}}\n",
        sv(&lts.initial)
    ));
    o
}

// --- Go ----------------------------------------------------------------------- //

fn go(lts: &Lts) -> String {
    let sv = |s: &str| vid(s);
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model export --lang go` — DO NOT EDIT.\n");
    o.push_str("package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n\t\"strings\"\n)\n\n");

    // States and events as int constants.
    o.push_str("type State int\ntype Event int\n\nconst (\n");
    for (i, s) in lts.states.iter().enumerate() {
        o.push_str(&format!("\tS_{} State = {}\n", sv(s), i));
    }
    o.push_str(")\nconst (\n");
    for (i, e) in lts.alphabet.iter().enumerate() {
        o.push_str(&format!("\tE_{} Event = {}\n", sv(e), i));
    }
    o.push_str(")\n\n");

    o.push_str("func step(s State, e Event) (State, bool) {\n\tswitch s {\n");
    for s in &lts.states {
        let arms: Vec<(String, String)> = lts
            .alphabet
            .iter()
            .filter_map(|e| lts.transitions.get(&(s.clone(), e.clone())).map(|t| (sv(e), sv(t))))
            .collect();
        if arms.is_empty() {
            continue;
        }
        o.push_str(&format!("\tcase S_{}:\n\t\tswitch e {{\n", sv(s)));
        for (e, t) in arms {
            o.push_str(&format!("\t\tcase E_{e}:\n\t\t\treturn S_{t}, true\n"));
        }
        o.push_str("\t\t}\n");
    }
    o.push_str("\t}\n\treturn s, false\n}\n\n");

    o.push_str("func name(s State) string {\n\tswitch s {\n");
    for s in &lts.states {
        o.push_str(&format!("\tcase S_{}:\n\t\treturn {:?}\n", sv(s), s));
    }
    o.push_str("\t}\n\treturn \"?\"\n}\n\n");

    o.push_str("func parseEvent(s string) (Event, bool) {\n\tswitch s {\n");
    for e in &lts.alphabet {
        o.push_str(&format!("\tcase {:?}:\n\t\treturn E_{}, true\n", e, sv(e)));
    }
    o.push_str("\t}\n\treturn 0, false\n}\n\n");

    o.push_str("func forbidden(s State) bool {\n\tswitch s {\n");
    for f in &lts.forbid {
        o.push_str(&format!("\tcase S_{}:\n\t\treturn true\n", sv(f)));
    }
    o.push_str("\t}\n\treturn false\n}\n\n");

    o.push_str(&format!(
        "func main() {{\n\
        \tsc := bufio.NewScanner(os.Stdin)\n\
        \tsc.Buffer(make([]byte, 1024*1024), 1024*1024)\n\
        \tfor sc.Scan() {{\n\
        \t\ts := S_{}\n\
        \t\tout := []string{{name(s)}}\n\
        \t\tif forbidden(s) {{ out = append(out, \"!\") }}\n\
        \t\tfor _, tok := range strings.Fields(sc.Text()) {{\n\
        \t\t\te, ok := parseEvent(tok)\n\
        \t\t\tif !ok {{ out = append(out, \"BADEVENT\"); break }}\n\
        \t\t\ts2, en := step(s, e)\n\
        \t\t\tif !en {{ out = append(out, \"BLOCKED\"); break }}\n\
        \t\t\ts = s2; out = append(out, name(s))\n\
        \t\t\tif forbidden(s) {{ out = append(out, \"!\") }}\n\
        \t\t}}\n\
        \t\tfmt.Println(strings.Join(out, \" \"))\n\
        \t}}\n}}\n",
        sv(&lts.initial)
    ));
    o
}
