//! FSM → Lean 4 exporter (PLAN-models §1.3) — the **M3** backend. Ported from
//! day48's `export_lean.py`. The exporter is deliberately dumb (PLAN-models §0
//! invariant 2): it transliterates a flat `Lts` into a self-contained Lean file
//! and lets the kernel re-derive the safety property. A wrong model produces a
//! proof that *fails to elaborate* — that is the teeth.
//!
//! Emitted shape, over a flat (possibly product-flattened) FSM:
//!   * `inductive State` (constructors = states) and `inductive Event`
//!   * `def step : State → Event → Option State` from the transition table,
//!     with `| _, _ => none` iff some (state, event) is genuinely blocked
//!   * `def safeB : State → Bool` (false exactly on the forbidden states)
//!   * `theorem safety` via `Fsm.invariant_of_preserved` + an exhaustive finite
//!     `cases <;> simp_all` — the kernel-checked analogue of the BFS in M1
//!   * `#print axioms safety` so the caller can certify sorry-free.

use super::ir::Lts;

/// Lean lowerCamel identifier from a model name: `goal_reached` → `goalReached`,
/// `Navigate|Delocalized` → `navigateDelocalized` (product states flatten). `|`
/// and `-` are treated as word separators alongside `_`.
fn ctor(name: &str) -> String {
    let norm = name.replace(['|', '-'], "_");
    let mut out = String::new();
    for (i, part) in norm.split('_').filter(|p| !p.is_empty()).enumerate() {
        let mut chars = part.chars();
        let head = chars.next().unwrap();
        if i == 0 {
            out.extend(head.to_lowercase());
        } else {
            out.extend(head.to_uppercase());
        }
        out.push_str(chars.as_str());
    }
    out
}

fn emit_inductive(typename: &str, names: &[String]) -> String {
    let mut s = format!("inductive {typename} where\n");
    for n in names {
        s.push_str(&format!("  | {}\n", ctor(n)));
    }
    s.push_str("  deriving DecidableEq, Repr\n");
    s
}

/// Emit the whole `.lean` file for the FSM `lts` under `namespace`.
pub fn emit_fsm(lts: &Lts, namespace: &str) -> String {
    let mut o = String::new();
    o.push_str(&format!(
        "/-\n  AUTO-GENERATED by leanlift `lift model prove` from a *.model.toml — DO NOT EDIT.\n  \
         The kernel re-derives, with a proof object, what the M1 BFS checked.\n-/\n\
         import LeanLift.Models.Fsm\n\nnamespace {namespace}\n\n"
    ));

    o.push_str(&emit_inductive("State", &lts.states));
    o.push('\n');
    o.push_str(&emit_inductive("Event", &lts.alphabet));
    o.push('\n');

    // step — one arm per defined transition; a catch-all `none` iff some
    // (state, event) pair is blocked (else Lean rejects the redundant arm).
    o.push_str("def step : State → Event → Option State\n");
    for s in &lts.states {
        for e in &lts.alphabet {
            if let Some(t) = lts.transitions.get(&(s.clone(), e.clone())) {
                o.push_str(&format!("  | .{}, .{} => some .{}\n", ctor(s), ctor(e), ctor(t)));
            }
        }
    }
    let some_blocked = lts
        .states
        .iter()
        .any(|s| lts.alphabet.iter().any(|e| !lts.transitions.contains_key(&(s.clone(), e.clone()))));
    if some_blocked {
        o.push_str("  | _, _ => none\n");
    }
    o.push('\n');

    o.push_str(&format!("def init : State := .{}\n\n", ctor(&lts.initial)));

    // safeB — false exactly on forbidden states, true otherwise.
    o.push_str("/-- Safety predicate (Bool so it computes under `simp`). -/\ndef safeB : State → Bool\n");
    for f in &lts.forbid {
        o.push_str(&format!("  | .{} => false\n", ctor(f)));
    }
    o.push_str("  | _ => true\n\n");

    // The safety theorem: base case `rfl`, preservation by exhaustive cases.
    o.push_str(
        "/-- Every reachable state is safe — base case `rfl`, preservation an\n\
        \x20   exhaustive finite case split (the kernel analogue of the M1 BFS). -/\n\
        theorem safety : ∀ s, LeanLift.Models.Fsm.Reachable init step s → safeB s = true :=\n\
        \x20 LeanLift.Models.Fsm.invariant_of_preserved (fun s => safeB s = true) rfl\n\
        \x20   (by\n\
        \x20     intro s e s' hs hstep\n\
        \x20     cases s <;> cases e <;>\n\
        \x20       simp_all [step, safeB] <;>\n\
        \x20       (try cases hstep) <;> (try subst_vars) <;> rfl)\n\n",
    );

    o.push_str(&format!("#print axioms {namespace}.safety\n\nend {namespace}\n"));
    o
}
