//! FSM → Lean 4 exporter (PLAN-models §1.3) — the **M3** backend. Ported from
//! day48's `export_lean.py`. The exporter is deliberately dumb (PLAN-models §0
//! invariant 2): it transliterates a flat `Lts` into a self-contained Lean file
//! and lets the kernel re-derive the safety property. A wrong model produces a
//! proof that *fails to elaborate* — that is the teeth.
//!
//! Emitted shape, over a flat (possibly product-flattened) FSM:
//!   * `inductive State` (constructors = states) and `inductive Event`
//!   * `def step : State → Event → Option State` from the transition table,
//!     with `| _, _ => none` iff some (state, event) is genuinely blocked
//!   * `def safeB : State → Bool` (false exactly on the forbidden states)
//!   * `theorem safety` via `Fsm.invariant_of_preserved` + an exhaustive finite
//!     `cases <;> simp_all` — the kernel-checked analogue of the BFS in M1
//!   * `#print axioms safety` so the caller can certify sorry-free.

use super::ir::{Lts, PtNet};

/// A valid Lean lowerCamel identifier from a model name: `goal_reached` →
/// `goalReached`, `Navigate|Delocalized` → `navigateDelocalized`. ANY
/// non-alphanumeric is a word boundary (so `a.b`, `cs A`, etc. stay valid Lean,
/// not just `|`/`-`/`_`); a digit-leading or empty name is prefixed so the
/// result is always a legal identifier. (Distinct names that sanitize to the
/// same identifier collide — the Lean kernel rejects that at elaboration rather
/// than silently; the executable codegen uses the underscore-preserving `vid`.)
fn ctor(name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            if out.is_empty() {
                if c.is_ascii_digit() {
                    out.push('s'); // identifiers cannot start with a digit
                    out.push(c);
                } else {
                    out.extend(c.to_lowercase());
                }
            } else if upper_next {
                out.extend(c.to_uppercase());
            } else {
                out.push(c);
            }
            upper_next = false;
        } else {
            upper_next = true; // a non-alphanumeric is a word boundary
        }
    }
    if out.is_empty() {
        out.push('x');
    }
    out
}

fn emit_inductive(typename: &str, names: &[String]) -> String {
    let mut s = format!("inductive {typename} where\n");
    for n in names {
        s.push_str(&format!("  | {}\n", ctor(n)));
    }
    s.push_str("  deriving DecidableEq, Repr\n");
    s
}

/// Emit the whole `.lean` file for the FSM `lts` under `namespace`.
pub fn emit_fsm(lts: &Lts, namespace: &str) -> String {
    let mut o = String::new();
    o.push_str(&format!(
        "/-\n  AUTO-GENERATED by leanlift `lift model prove` from a *.model.toml — DO NOT EDIT.\n  \
         The kernel re-derives, with a proof object, what the M1 BFS checked.\n-/\n\
         import LeanLift.Models.Fsm\n\nnamespace {namespace}\n\n"
    ));

    o.push_str(&emit_inductive("State", &lts.states));
    o.push('\n');
    o.push_str(&emit_inductive("Event", &lts.alphabet));
    o.push('\n');

    // step — one arm per defined transition; a catch-all `none` iff some
    // (state, event) pair is blocked (else Lean rejects the redundant arm). A
    // model with no events at all (e.g. a BT that is immediately quiescent) has
    // an empty `Event`, so `step` is written via `nomatch`.
    if lts.alphabet.is_empty() {
        o.push_str("def step : State → Event → Option State := fun _ e => nomatch e\n");
    } else {
        o.push_str("def step : State → Event → Option State\n");
        for s in &lts.states {
            for e in &lts.alphabet {
                if let Some(t) = lts.transitions.get(&(s.clone(), e.clone())) {
                    o.push_str(&format!("  | .{}, .{} => some .{}\n", ctor(s), ctor(e), ctor(t)));
                }
            }
        }
        let some_blocked = lts.states.iter().any(|s| {
            lts.alphabet.iter().any(|e| !lts.transitions.contains_key(&(s.clone(), e.clone())))
        });
        if some_blocked {
            o.push_str("  | _, _ => none\n");
        }
    }
    o.push('\n');

    o.push_str(&format!("def init : State := .{}\n\n", ctor(&lts.initial)));

    // safeB — false exactly on forbidden states, true otherwise.
    o.push_str("/-- Safety predicate (Bool so it computes under `simp`). -/\ndef safeB : State → Bool\n");
    for f in &lts.forbid {
        o.push_str(&format!("  | .{} => false\n", ctor(f)));
    }
    o.push_str("  | _ => true\n\n");

    // The safety theorem: base case `rfl`, preservation by exhaustive cases.
    o.push_str(
        "/-- Every reachable state is safe — base case `rfl`, preservation an\n\
        \x20   exhaustive finite case split (the kernel analogue of the M1 BFS). -/\n\
        theorem safety : ∀ s, LeanLift.Models.Fsm.Reachable init step s → safeB s = true :=\n\
        \x20 LeanLift.Models.Fsm.invariant_of_preserved (fun s => safeB s = true) rfl\n\
        \x20   (by\n\
        \x20     intro s e s' hs hstep\n\
        \x20     cases s <;> cases e <;>\n\
        \x20       simp_all [step, safeB] <;>\n\
        \x20       (try cases hstep) <;> (try subst_vars) <;> rfl)\n\n",
    );

    o.push_str(&format!("#print axioms {namespace}.safety\n\nend {namespace}\n"));
    o
}

/// PT-net → Lean (PLAN-models §2.3) — the **M3** backend for Petri nets with
/// loss. Ported from day48's `export_petri.py`. The proof strategy is the
/// safety-survives-loss lesson made formal: prove the *inductive* upper bound
/// `total m ≤ B` (B = initial token mass — every transition conserves or, under
/// loss, decreases the total), then derive each declared bound by `omega`. A
/// non-conservative transition (more produced than consumed) makes `total ≤ B`
/// non-inductive and the proof fails — which is honest (out of Phase-2 scope).
pub fn emit_petri(net: &PtNet, namespace: &str) -> String {
    let field = |i: usize| ctor(&net.places[i]);
    let np = net.places.len();
    // The invariant is over the conserved subsystem (a place invariant); the
    // default is all places (the dock's global token total).
    let conserved: Vec<usize> = net.conserved.clone().unwrap_or_else(|| (0..np).collect());
    let b: u32 = conserved.iter().map(|&i| net.initial[i]).sum();

    let mut o = String::new();
    o.push_str(&format!(
        "/-\n  AUTO-GENERATED by leanlift `lift model prove` from a *.model.toml — DO NOT EDIT.\n  \
         PT-net with loss: the kernel re-derives the M1 BFS as a checked proof object.\n  \
         Safety is an UPPER BOUND (monotone under loss), proved via the inductive\n  \
         strengthening `total ≤ {b}`.\n-/\n\
         import LeanLift.Models.Petri\nimport LeanLift.Models.Fsm\n\nnamespace {namespace}\n\n"
    ));

    // inductive Place / Tr (documentation parity with day48; the proof works
    // over `structure M` so `omega` sees plain Nat arithmetic per place).
    o.push_str(&emit_inductive("Place", &net.places));
    o.push('\n');
    let tr_names: Vec<String> = net.transitions.iter().map(|t| t.name.clone()).collect();
    o.push_str(&emit_inductive("Tr", &tr_names));
    o.push('\n');

    // structure M — one Nat field per place.
    o.push_str("structure M where\n");
    for i in 0..np {
        o.push_str(&format!("  {} : Nat\n", field(i)));
    }
    o.push_str("  deriving DecidableEq, Repr\n\n");

    // step — guarded record update per transition.
    o.push_str("def step (m : M) : Tr → Option M\n");
    for t in &net.transitions {
        let guards: Vec<String> = (0..np)
            .filter(|&i| t.pre[i] > 0)
            .map(|i| format!("{} ≤ m.{}", t.pre[i], field(i)))
            .collect();
        let guard = if guards.is_empty() { "True".to_string() } else { guards.join(" ∧ ") };
        let updates: Vec<String> = (0..np)
            .map(|i| {
                let mut e = format!("m.{}", field(i));
                if t.pre[i] > 0 {
                    e.push_str(&format!(" - {}", t.pre[i]));
                }
                if t.post[i] > 0 {
                    e.push_str(&format!(" + {}", t.post[i]));
                }
                format!("{} := {}", field(i), e)
            })
            .collect();
        o.push_str(&format!(
            "  | .{} => if {} then some {{ {} }} else none\n",
            ctor(&t.name),
            guard,
            updates.join(", ")
        ));
    }
    o.push('\n');

    // init.
    let inits: Vec<String> = (0..np).map(|i| format!("{} := {}", field(i), net.initial[i])).collect();
    o.push_str(&format!("def init : M := {{ {} }}\n\n", inits.join(", ")));

    // total + the inductive upper-bound invariant, over the conserved subsystem.
    let total_expr: Vec<String> = conserved.iter().map(|&i| format!("m.{}", field(i))).collect();
    o.push_str(&format!(
        "/-- Conserved token mass (a place invariant): every transition keeps this\n\
        \x20   equal or (loss) decreases it — never grows. -/\n\
        def total (m : M) : Nat := {}\n\n\
        /-- The UPPER-BOUND invariant: the conserved mass starts at {b} and never grows. -/\n\
        def Inv (m : M) : Prop := total m ≤ {b}\n\n",
        total_expr.join(" + ")
    ));

    // safeB — conjunction of declared bounds (or `true` if none declared).
    let has_bounds = !net.bounds.is_empty();
    if has_bounds {
        let conj: Vec<String> = net
            .bounds
            .iter()
            .map(|bd| {
                let sum: Vec<String> = bd.places.iter().map(|&i| format!("m.{}", field(i))).collect();
                format!("{} ≤ {}", sum.join(" + "), bd.max)
            })
            .collect();
        o.push_str(&format!(
            "/-- The declared safety property (upper bounds ⇒ e.g. mutual exclusion). -/\n\
            def safeB (m : M) : Bool := decide ({})\n\n",
            conj.join(" ∧ ")
        ));
    } else {
        o.push_str("def safeB (_ : M) : Bool := true\n\n");
    }

    // inv_holds — base by simp, preservation by exhaustive cases + split + omega.
    o.push_str(
        "/-- `Inv` holds in every reachable marking: base by `simp`; preservation\n\
        \x20   fires any transition and `omega` keeps the bound (it splits the firing\n\
        \x20   guard and uses `Inv m`). The kernel analogue of the M1 BFS. -/\n\
        theorem inv_holds : ∀ m, LeanLift.Models.Fsm.Reachable init step m → Inv m :=\n\
        \x20 LeanLift.Models.Fsm.invariant_of_preserved Inv (by simp [Inv, total, init])\n\
        \x20   (by\n\
        \x20     intro m t m' hI hstep\n\
        \x20     simp only [Inv, total] at hI ⊢\n\
        \x20     cases t <;>\n\
        \x20       simp only [step] at hstep <;>\n\
        \x20       split at hstep <;>\n\
        \x20       first\n\
        \x20         | (injection hstep with h; subst h; simp only []; omega)\n\
        \x20         | simp at hstep)\n\n",
    );

    // safety — derive the declared bound(s) from Inv by omega.
    if has_bounds {
        o.push_str(
            "/-- THE safety theorem: the declared upper bound holds in every reachable\n\
            \x20   marking — and SURVIVES token loss, being a corollary of the\n\
            \x20   upper-bound `Inv`, not of any conservation equality. -/\n\
            theorem safety : ∀ m, LeanLift.Models.Fsm.Reachable init step m → safeB m = true := by\n\
            \x20 intro m h\n\
            \x20 have hI := inv_holds m h\n\
            \x20 simp only [Inv, total] at hI\n\
            \x20 simp only [safeB, decide_eq_true_eq]\n\
            \x20 omega\n\n",
        );
    } else {
        o.push_str(
            "theorem safety : ∀ m, LeanLift.Models.Fsm.Reachable init step m → safeB m = true := by\n\
            \x20 intro m _; rfl\n\n",
        );
    }

    o.push_str(&format!("#print axioms {namespace}.safety\n\nend {namespace}\n"));
    o
}
