//! GSPN → PRISM/Storm export (PLAN-models §5.4). The quantitative twin of the
//! Lean exporters: instead of a proof we emit a **model + CSL queries** a
//! probabilistic model checker re-derives. We export the *tangible* CTMC
//! directly (vanishing markings pre-eliminated, §5.2) as an explicit-state PRISM
//! `ctmc` module — so the rates are the concrete `Q` we solved, and PRISM
//! reproduces our numbers (the proper independent machine-check). When no PRISM
//! binary is present, the native solver (`gspn.rs`) is the self-check.

use super::gspn::{Compute, Gspn, Query};

fn dec(s: &str) -> Vec<u32> {
    s.split(',').map(|x| x.parse().unwrap_or(0)).collect()
}

/// Format an f64 rate compactly for PRISM (`1`, `0.5`, `1.5`).
fn rate(x: f64) -> String {
    let s = format!("{x}");
    s
}

/// The `.prism` CTMC model: one explicit state variable over the tangible
/// markings, one grouped command per source state, a `time` reward, and a label
/// per query target plus an `absorbing` label.
pub fn emit_model(net: &Gspn, tang: &[String], q: &[Vec<f64>], start: usize) -> String {
    let n = tang.len();
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model prism` — the tangible CTMC.\n");
    o.push_str(&format!("// {} mode; {n} tangible state(s). Check: prism model.prism model.props\n", net.mode));
    o.push_str("ctmc\n\nmodule chain\n");
    o.push_str(&format!("  s : [0..{}] init {start};\n\n", n.saturating_sub(1)));
    for i in 0..n {
        let edges: Vec<String> = (0..n)
            .filter(|&j| j != i && q[i][j].abs() > 1e-15)
            .map(|j| format!("{} : (s'={j})", rate(q[i][j])))
            .collect();
        if !edges.is_empty() {
            o.push_str(&format!("  [] s={i} -> {};\n", edges.join(" + ")));
        }
    }
    o.push_str("endmodule\n\n");
    o.push_str("rewards \"time\"\n  true : 1;\nendrewards\n\n");

    // labels: one per distinct query target, plus the absorbing class.
    let mut targets: Vec<usize> = net.queries.iter().filter_map(|qq| qq.target).collect();
    targets.sort();
    targets.dedup();
    for t in targets {
        let states: Vec<String> = tang
            .iter()
            .enumerate()
            .filter(|(_, m)| dec(m)[t] > 0)
            .map(|(i, _)| format!("s={i}"))
            .collect();
        let body = if states.is_empty() { "false".to_string() } else { states.join(" | ") };
        o.push_str(&format!("label \"{}\" = {body};\n", net.places[t]));
    }
    let absorb: Vec<String> = (0..n)
        .filter(|&i| (0..n).all(|j| q[i][j].abs() < 1e-15))
        .map(|i| format!("s={i}"))
        .collect();
    let abody = if absorb.is_empty() { "false".to_string() } else { absorb.join(" | ") };
    o.push_str(&format!("label \"absorbing\" = {abody};\n"));
    o
}

/// The `.props` CSL/PCTL queries, one per `[[query]]`.
pub fn emit_props(net: &Gspn) -> String {
    let mut o = String::new();
    o.push_str("// AUTO-GENERATED by leanlift `lift model prism` — CSL queries.\n\n");
    for q in &net.queries {
        o.push_str(&format!("// {}\n", q.name));
        o.push_str(&csl(net, q));
        o.push('\n');
    }
    o
}

fn csl(net: &Gspn, q: &Query) -> String {
    match q.compute {
        Compute::Prob => {
            let t = &net.places[q.target.expect("prob needs target")];
            format!("P=? [ F \"{t}\" ];\n")
        }
        Compute::Etime => "R{\"time\"}=? [ F \"absorbing\" ];\n".to_string(),
        Compute::Transient => {
            let t = &net.places[q.target.expect("transient needs target")];
            let time = q.time.expect("transient needs time");
            format!("P=? [ F<={time} \"{t}\" ];\n")
        }
    }
}
