//! The source oracle (SPEC §6): the source implementation is ground truth.
//! Dispatch by language:
//!   - C++ / Go: compile source + a generated typed runner, execute per vector.
//!     The compiler emits the correct ABI for any arity/width. These languages
//!     WRAP on unsigned overflow, so the oracle always returns a number.
//!   - Solidity: execute on an EVM (see `oracle_sol`). Checked arithmetic can
//!     REVERT, so the oracle may emit the `OVERFLOW` token like the Lean side.
//!
//! Results come back as a map from input key (`"a b c …"`) to a decimal string
//! or the `OVERFLOW` token.

use crate::lang::Lang;
use crate::sig::Signature;
use crate::vectors::Vector;
use std::collections::HashMap;
use std::io::Write;
use std::path::Path;
use std::process::Command;

pub fn run(
    lang: Lang,
    source: &Path,
    symbol: &str,
    sig: &Signature,
    vectors: &[Vector],
    work_dir: &Path,
) -> Result<HashMap<String, String>, String> {
    let vec_file = write_vectors(vectors, work_dir)?;
    match lang {
        Lang::Cpp => oracle_cpp(source, symbol, sig, &vec_file, work_dir),
        Lang::Go => oracle_go(source, symbol, sig, &vec_file, work_dir),
        Lang::Solidity => crate::oracle_sol::run(source, symbol, sig, vectors, work_dir),
    }
}

fn write_vectors(vectors: &[Vector], work_dir: &Path) -> Result<std::path::PathBuf, String> {
    let vec_file = work_dir.join("vectors.txt");
    let mut f =
        std::fs::File::create(&vec_file).map_err(|e| format!("cannot write vectors: {e}"))?;
    for v in vectors {
        writeln!(f, "{}", v.key()).unwrap();
    }
    Ok(vec_file)
}

/// Parse `args => result` lines from a runner's stdout into the result map.
fn parse_lines(stdout: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    for line in stdout.lines() {
        if let Some((lhs, rhs)) = line.split_once("=>") {
            map.insert(lhs.trim().to_string(), rhs.trim().to_string());
        }
    }
    map
}

// ---- C++ -------------------------------------------------------------------

fn oracle_cpp(
    source: &Path,
    symbol: &str,
    sig: &Signature,
    vec_file: &Path,
    work_dir: &Path,
) -> Result<HashMap<String, String>, String> {
    let runner = work_dir.join("oracle_runner.cpp");
    std::fs::write(&runner, cpp_runner(symbol, sig))
        .map_err(|e| format!("cannot write runner: {e}"))?;
    let bin = work_dir.join("oracle_cpp");
    let st = Command::new("clang++")
        .args(["-std=c++23", "-O2"])
        .arg(&runner)
        .arg(source)
        .arg("-o")
        .arg(&bin)
        .status()
        .map_err(|e| format!("failed to invoke clang++: {e}"))?;
    if !st.success() {
        return Err(format!("clang++ failed to build the oracle for {}", source.display()));
    }
    run_bin(&bin, vec_file)
}

fn cpp_runner(symbol: &str, sig: &Signature) -> String {
    let n = sig.arity();
    let arg_decl = sig.args.iter().map(|t| t.c_name()).collect::<Vec<_>>().join(", ");
    let scan_fmt = vec!["%llu"; n].join(" ");
    let scan_addr = (0..n).map(|i| format!("&a{i}")).collect::<Vec<_>>().join(", ");
    let call_args =
        (0..n).map(|i| format!("({})a{i}", sig.args[i].c_name())).collect::<Vec<_>>().join(", ");
    let print_fmt = format!("{} => %llu\\n", vec!["%llu"; n].join(" "));
    let print_args = {
        let mut s = (0..n).map(|i| format!("a{i}")).collect::<Vec<_>>();
        s.push("(unsigned long long)r".to_string());
        s.join(", ")
    };
    let decls = (0..n).map(|i| format!("unsigned long long a{i}=0;")).collect::<Vec<_>>().join(" ");
    format!(
        "// generated by leanlift — typed differential-test runner\n\
         #include <cstdint>\n#include <cstdio>\n\n\
         extern \"C\" {ret} {symbol}({arg_decl});\n\n\
         int main(int argc, char** argv) {{\n\
         \x20 if (argc < 2) return 2;\n\
         \x20 FILE* f = fopen(argv[1], \"r\");\n  if (!f) return 3;\n\
         \x20 char line[8192];\n\
         \x20 while (fgets(line, sizeof line, f)) {{\n\
         \x20   {decls}\n\
         \x20   if (sscanf(line, \"{scan_fmt}\", {scan_addr}) != {n}) continue;\n\
         \x20   {ret} r = {symbol}({call_args});\n\
         \x20   printf(\"{print_fmt}\", {print_args});\n\
         \x20 }}\n  return 0;\n}}\n",
        ret = sig.ret.c_name(),
    )
}

// ---- Go --------------------------------------------------------------------

fn oracle_go(
    source: &Path,
    symbol: &str,
    sig: &Signature,
    vec_file: &Path,
    work_dir: &Path,
) -> Result<HashMap<String, String>, String> {
    // Go is one-package-per-dir: stage the kernel + a generated main together.
    let dir = work_dir.join("go-oracle");
    let _ = std::fs::create_dir_all(&dir);
    std::fs::copy(source, dir.join("kernel.go"))
        .map_err(|e| format!("cannot stage go source: {e}"))?;
    std::fs::write(dir.join("runner.go"), go_runner(symbol, sig))
        .map_err(|e| format!("cannot write go runner: {e}"))?;
    std::fs::write(dir.join("go.mod"), "module leanlift_oracle\n\ngo 1.20\n")
        .map_err(|e| format!("cannot write go.mod: {e}"))?;

    let bin = dir.join("oracle_go");
    let st = Command::new("go")
        .args(["build", "-o"])
        .arg(&bin)
        .arg(".")
        .current_dir(&dir)
        .status()
        .map_err(|e| format!("failed to invoke go: {e}"))?;
    if !st.success() {
        return Err(format!("go build failed for {}", source.display()));
    }
    run_bin(&bin, vec_file)
}

fn go_runner(symbol: &str, sig: &Signature) -> String {
    let n = sig.arity();
    let decls = (0..n).map(|i| format!("a{i}")).collect::<Vec<_>>().join(", ");
    let addrs = (0..n).map(|i| format!("&a{i}")).collect::<Vec<_>>().join(", ");
    let call = (0..n)
        .map(|i| format!("{}(a{i})", sig.args[i].go_name()))
        .collect::<Vec<_>>()
        .join(", ");
    let fmt = format!("{} => %d\\n", vec!["%d"; n].join(" "));
    let print_args = {
        let mut s = (0..n).map(|i| format!("a{i}")).collect::<Vec<_>>();
        s.push("uint64(r)".to_string());
        s.join(", ")
    };
    format!(
        "// generated by leanlift — typed differential-test runner\n\
         package main\n\nimport (\n\t\"bufio\"\n\t\"fmt\"\n\t\"os\"\n)\n\n\
         func main() {{\n\
         \tf, err := os.Open(os.Args[1])\n\tif err != nil {{ os.Exit(3) }}\n\tdefer f.Close()\n\
         \tsc := bufio.NewScanner(f)\n\tsc.Buffer(make([]byte, 1024*1024), 1024*1024)\n\
         \tfor sc.Scan() {{\n\
         \t\tvar {decls} uint64\n\
         \t\tnn, _ := fmt.Sscan(sc.Text(), {addrs})\n\
         \t\tif nn != {n} {{ continue }}\n\
         \t\tr := {symbol}({call})\n\
         \t\tfmt.Printf(\"{fmt}\", {print_args})\n\
         \t}}\n}}\n",
    )
}

// ---- shared ----------------------------------------------------------------

fn run_bin(bin: &Path, vec_file: &Path) -> Result<HashMap<String, String>, String> {
    let out = Command::new(bin)
        .arg(vec_file)
        .output()
        .map_err(|e| format!("failed to run oracle: {e}"))?;
    if !out.status.success() {
        return Err(format!("oracle runner exited with {}", out.status));
    }
    Ok(parse_lines(&String::from_utf8_lossy(&out.stdout)))
}
